/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.dukecon.server.api.model {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.dukecon.server.api.model.TalkData$Language")]
    public class TalkData$Language extends Enum {

        public static const DE:TalkData$Language = new TalkData$Language("DE", _);
        public static const EN:TalkData$Language = new TalkData$Language("EN", _);

        function TalkData$Language(value:String = null, restrictor:* = null) {
            super((value || DE.name), restrictor);
        }

        protected override function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [DE, EN];
        }

        public static function valueOf(name:String):TalkData$Language {
            return TalkData$Language(DE.constantOf(name));
        }
    }
}