/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.dukecon.model {

    [RemoteClass(alias="org.dukecon.model.Language")]
    public class Language extends LanguageBase {

        public function Language(obj:Object = null) {
            super(obj);
        }

    }
}