/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.dukecon.model {

    [RemoteClass(alias="org.dukecon.model.Resources")]
    public class Resources extends ResourcesBase {
    }
}