/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.dukecon.model {

[RemoteClass(alias="org.dukecon.model.Track")]
public class Track extends TrackBase {

    public function Track(obj:Object = null) {
        super(obj);
    }
    
    public function getName(locale:String):String {
        var parts:Array = locale.split("_");
        return names[parts[0]];
    }

}
}