/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.dukecon.model {

[RemoteClass(alias="org.dukecon.model.UserPreference")]
public class UserPreference extends UserPreferenceBase {

    public function UserPreference(obj:Object = null) {
        super(obj);
    }

}
}