/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.dukecon.model.user {

    [RemoteClass(alias="org.dukecon.model.user.UserFilters")]
    public class UserFilters extends UserFiltersBase {

        public function UserFilters(obj:Object = null) {
            super(obj);
        }

    }
}