/**
 * Generated by Gas3 v${gVersion} (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ${jClass.as3Type.packageName} {

public class ${jClass.as3Type.name}Helper {

}
}